import type { LucideIcon } from 'lucide-react';
import {
  AlignLeft,
  BarChart2,
  ChevronsDownUp,
  Code2,
  Columns2,
  FileText,
  Gauge,
  Heading,
  Newspaper,
  Rows3,
  Image as ImageIcon,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Layers,
  Lightbulb,
  ClipboardList,
  Map,
  MapPinned,
  Menu,
  Minus,
  MousePointerClick,
  MoveVertical,
  PanelBottom,
  Share2,
  Sparkles,
  Table2,
  UsersRound,
  Video,
} from 'lucide-react';
import type { BlockType } from '@/lib/editor-types';

/** Ícone de linha fina por tipo de bloco (referência estilo Elementor). */
export const EDITOR_PALETTE_ICONS: Record<BlockType, LucideIcon> = {
  'site-header': Menu,
  'site-footer': PanelBottom,
  'hero-section': Sparkles,
  'system-section': Layers,
  'segments-section': LayoutGrid,
  'solutions-section': Lightbulb,
  'stats-section': BarChart2,
  'partners-section': UsersRound,
  'contact-hero-split': LayoutPanelLeft,
  'contact-form-split': ClipboardList,
  'contact-map-split': MapPinned,
  'contact-social-strip': Share2,
  'blog-featured': Newspaper,
  'blog-posts-grid': Rows3,
  'free-text': AlignLeft,
  'rich-text': FileText,
  image: ImageIcon,
  spacer: MoveVertical,
  'layout-section': LayoutTemplate,
  'layout-columns': Columns2,
  'layout-divider': Minus,
  'heading-block': Heading,
  'button-block': MousePointerClick,
  'video-embed': Video,
  'map-embed': Map,
  'accordion-block': ChevronsDownUp,
  'tabs-simple': LayoutPanelTop,
  'progress-block': Gauge,
  'pricing-table': Table2,
  'rich-html': Code2,
};
